### ISSUE TITLE
Plugin Errors on color keywords in font family names like "Arial Black"

### ISSUE THREAD

**Issue by carlosjeurissen** [ierhyna/stylelint-no-indistinguishable-colors#19]
Since version 2.0.0, the following code:
`font-family: Helvetica, "Arial Black", sans-serif;`

Will cause Circular reference error with the following stacktrace:
```
at <input css RJ9aru>:72:5
at x (/colorguard-processor@1.0.48/node_modules/colorguard-processor/dist/index.js:36:3395)
at h (/colorguard-processor@1.0.48/node_modules/colorguard-processor/dist/index.js:36:2744)
at u (/colorguard-processor@1.0.48/node_modules/colorguard-processor/dist/index.js:37:222)
at /colorguard-processor@1.0.48/node_modules/colorguard-processor/dist/index.js:37:842
at Array.forEach (<anonymous>)
at /colorguard-processor@1.0.48/node_modules/colorguard-processor/dist/index.js:37:772
at Array.forEach (<anonymous>)
at /colorguard-processor@1.0.48/node_modules/colorguard-processor/dist/index.js:37:634
at /postcss@8.4.33/node_modules/postcss/lib/container.js:345:18
at /postcss@8.4.33/node_modules/postcss/lib/container.js:297:18
```

Seems somehow it recognises color names in font family names and result into errors.

This error was not present in v1.3.2.

**Comment by carlosjeurissen** [comment]
@ierhyna Did some additional research. Seems the issue got introduced in colorguard-processor v1.0.34. So v1.0.33 is the last version which does not contain this issue. So apologies for reporting it here.

See also:
https://github.com/SlexAxton/css-colorguard/issues/59#issuecomment-1906208639
